---
extends: default

ignore: |
  **/*-base.yml

rules:
  braces:
    min-spaces-inside: 0
    max-spaces-inside: 0
  brackets:
    min-spaces-inside: 0
    max-spaces-inside: 0
  colons:
    max-spaces-after: 1
  commas:
    max-spaces-after: 1
  comments:
    min-spaces-from-content: 1
  document-end:
    present: false
  document-start:
    present: true
  empty-lines:
    max: 2
    max-end: 1
  hyphens:
    max-spaces-after: 1
  indentation:
    spaces: 2
    indent-sequences: consistent
  line-length: disable
  new-line-at-end-of-file: enable
  new-lines:
    type: unix
  trailing-spaces: enable
  truthy:
    allowed-values: ['true', 'false']
    check-keys: true
