apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: launcher
  namespace: argocd
spec:
  destination:
    namespace: argocd
    server: https://kubernetes.default.svc
  project: default
  source:
    directory:
      recurse: true
    path: .launcher
    repoURL: https://github.com/rezachalak/argocd-workshop.git
    targetRevision: HEAD
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
