apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: launcher
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: This project hosts all the resources responsible for bootstraping cluster configuration
  destinations:
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
