apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: apollo11
  namespace: argocd
spec:
  clusterResourceWhitelist:
    - group: "*"
      kind: "*"
  description: This project hosts all the resources responsible for apollo11
  destinations:
    - namespace: "*"
      server: "*"
  namespaceResourceWhitelist:
    - group: "*"
      kind: "*"
  sourceRepos:
    - "*"
